# netlify.toml
[build]
  publish   = "."
  functions = "netlify/functions"
  command   = ""

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"   # <-- uten punktum foran
  status = 200
