# netlify.toml
[build]
  publish   = "."
  functions = "netlify/functions"
  command   = ""

[build.environment]
  GITHUB_OWNER = "Luckywolf82"
  GITHUB_REPO  = "vcards-admin-branding"
  BASE_PATH    = "Vcards"
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"   # <-- uten punktum foran
  status = 200

[[redirects]]
  from = "/api/deleteFile"
  to   = "/.netlify/functions/deleteFile"
  status = 200
